### ISSUE TITLE
Error: ‘data’ not found, and some variables missing from formula environment

### ISSUE THREAD

**Issue by BastienFR** [jslefche/rsquared.glmm#3]
I’ve found a little annoyance (bug) that I would like to point out. In some situation, i.e. when the “data” object doesn’t exist in the global environment, the function fails with: Error: ‘data’ not found, and some variables missing from formula environment

This is (I think) caused by the update fonction you use at line 70 (for sure) and maybe also 90 and 133. It seems the update() function goes to look for the data in the global environment and not in the model object (“mdl”). I’ve fixed the problem by changing the command with: mdl.aic = AIC(update(mdl, method=”ML”, data=mdl@frame))

I had the problem because I was running multiple lmer() on a list of dataframe with an homemade function. My model data was therefore named with the name of my function argument and not of the original dataset.

**Comment by BastienFR** [comment]
Just a tiny addition, to test it,  just run your code adding rm(data) just before you call rsquared.glmm().

it will fail.

But if you implement the modification I proposed to you, it passes.

I think it's an improvment, but you'll need to make sure it doesn't break anything else, as I'm not that familliar with your coding.

Thanks again.

**Comment by jslefche** [comment]
Not all model classes store the data in the object, so going to leave this is as for now. But thanks for bringing to my attention
