### ISSUE TITLE
Not work for more than 3 random effects

### ISSUE THREAD

**Issue by yangjl** [jslefche/rsquared.glmm#4]
Hi,

When I ran your 'rsquared.glmm' with more than 3 random variable, it threw me the following error:

Error in `[.data.frame`(mdl@frame, , l) : undefined columns selected

**Comment by jslefche** [comment]
Can reproduce:
```
data = data.frame(
  y = runif(100, 0, 1),
  x = runif(100, 0, 1),
  rand1 = letters[1:2],
  rand2 = rep(letters[3:4], each = 50),
  rand3 = rep(letters[5:14], each = 10)
)

library(lme4)

model = lmer(y ~ x + (1|rand1) + (1|rand2) + (1|rand3), data)

rsquared.glmm(model)

nested.model = lmer(y ~ x + (1|rand1/rand2/rand3), data)

rsquared.glmm(nested.model)
```

See updated function here: https://github.com/jslefche/piecewiseSEM/blob/master/R/sem.model.fits.R
